title: Vit-On-Job 
description: Vit-On-Job, une technologie avancée au service du réseau des réseaux de l'emploi.
show_downloads: true
google_analytics:
zip_url:employeur.github.io
tar_url:jobyer.github.io
theme: jekyll-theme-cayman
